apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  namespace: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
          image: 596660701410.dkr.ecr.us-east-1.amazonaws.com/my-app:fc09c4f23d2e2fd104d216058304f15e44c84e4a
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
