apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-app
  namespace: swiggy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-app
          image: 596660701410.dkr.ecr.us-east-1.amazonaws.com/my-app:fd74455f2bb3ae6d3904e78f2aa440f61a45f9bd
          ports:
            - containerPort: 1234
          readinessProbe:
            httpGet:
              path: /health
              port: 1234
            initialDelaySeconds: 5
            periodSeconds: 10
