apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  namespace: swiggy
spec:
  type: NodePort
  selector:
    app: swiggy-app
  ports:
    - port: 80        # internal cluster port
      targetPort: 80  # must match containerPort in Deployment
      nodePort: 30001 # port on the node to expose externally
